trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo "New Azure DevOps Pipeline Created Successfully"

- bash: |
    echo "Pipeline Triggered from GitHub Changes"
    date
  displayName: 'Run Build'