trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo "Building Application..."
    mkdir build
    echo "Sample App Files" > build/app.txt
  displayName: 'Build Application'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

- script: |
    echo "Deploying Application..."
    echo "Deployment Successful"
  displayName: 'Release Deployment'